//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFOnlineCodes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RFOnlineCodes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;iabba01&apos;,&apos;Fire_Parsal_AppendixA(1)&apos;
        ///&apos;1&apos;,&apos;iabba02&apos;,&apos;Fire_Parsal_AppendixB(2)&apos;
        ///&apos;2&apos;,&apos;iabba03&apos;,&apos;Fire_Parsal_AppendixC(3)&apos;
        ///&apos;3&apos;,&apos;iabba04&apos;,&apos;Fire_Parsal_AppendixD(4)&apos;
        ///&apos;4&apos;,&apos;iabba05&apos;,&apos;Fire_Parsal_AppendixE(5)&apos;
        ///&apos;5&apos;,&apos;iabba06&apos;,&apos;Fire_Parsal_AppendixF(6)&apos;
        ///&apos;6&apos;,&apos;iabba07&apos;,&apos;Fire_Parsal_AppendixG(7)&apos;
        ///&apos;7&apos;,&apos;iabba08&apos;,&apos;Aqua_Parsal_AppendixA(1)&apos;
        ///&apos;8&apos;,&apos;iabba09&apos;,&apos;Aqua_Parsal_AppendixB(2)&apos;
        ///&apos;9&apos;,&apos;iabba10&apos;,&apos;Aqua_Parsal_AppendixC(3)&apos;
        ///&apos;10&apos;,&apos;iabba11&apos;,&apos;Aqua_Parsal_AppendixD(4)&apos;
        ///&apos;11&apos;,&apos;iabba12&apos;,&apos;Aqua_Parsal_AppendixE(5)&apos;
        ///&apos;12&apos;,&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AmuletItem {
            get {
                return ResourceManager.GetString("AmuletItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;ijccc01&apos;,&apos;Paimon&apos;
        ///&apos;1&apos;,&apos;ijccc02&apos;,&apos;Hecate&apos;
        ///&apos;2&apos;,&apos;ijccc03&apos;,&apos;Inanna&apos;
        ///&apos;3&apos;,&apos;ijccc04&apos;,&apos;Isis&apos;
        ///&apos;4&apos;,&apos;ijccc05&apos;,&apos;Sealed-Paimon&apos;
        ///&apos;5&apos;,&apos;ijccc06&apos;,&apos;Sealed-Hecate&apos;
        ///&apos;6&apos;,&apos;ijccc07&apos;,&apos;Sealed-Inanna&apos;
        ///&apos;7&apos;,&apos;ijccc08&apos;,&apos;Sealed-Isis&apos;.
        /// </summary>
        internal static string AnimusItem {
            get {
                return ResourceManager.GetString("AnimusItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;iebbs00&apos;,&apos;Training_Bag(Bellato)&apos;
        ///&apos;1&apos;,&apos;ieccs00&apos;,&apos;Training_Bag(Cora)&apos;
        ///&apos;2&apos;,&apos;ieaas00&apos;,&apos;Training_Bag(Accretia)&apos;
        ///&apos;3&apos;,&apos;iebbb00&apos;,&apos;Bag(Bellato)&apos;
        ///&apos;4&apos;,&apos;ieccc00&apos;,&apos;Bag(Cora)&apos;
        ///&apos;5&apos;,&apos;ieaaa00&apos;,&apos;Bag(Accretia)&apos;.
        /// </summary>
        internal static string BagItem {
            get {
                return ResourceManager.GetString("BagItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;itttt00&apos;,&apos;Training_Mining_Tool_Battery_[S]&apos;
        ///&apos;1&apos;,&apos;itttt01&apos;,&apos;Mining_Tool_Battery_[S]&apos;
        ///&apos;2&apos;,&apos;itttt02&apos;,&apos;Mining_Tool_Battery_[M]&apos;
        ///&apos;3&apos;,&apos;itttt03&apos;,&apos;Mining_Tool_Battery_[L]&apos;
        ///&apos;4&apos;,&apos;ittwe01&apos;,&apos;ChunjangZoneBattery&apos;
        ///&apos;5&apos;,&apos;itdbr01&apos;,&apos;Fullmoon_Large_Mining_Battery&apos;
        ///&apos;6&apos;,&apos;itttt04&apos;,&apos;UMT_Battery_[S]&apos;
        ///&apos;7&apos;,&apos;itttt05&apos;,&apos;UMT_Battery_[M]&apos;
        ///&apos;8&apos;,&apos;itcsa01&apos;,&apos;UMT_Battery_[L]&apos;
        ///&apos;9&apos;,&apos;itcsa02&apos;,&apos;Unmanned_Mining_Tool_Battery[Extra-Large]&apos;.
        /// </summary>
        internal static string BatteryItem {
            get {
                return ResourceManager.GetString("BatteryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;ixbdn25&apos;,&apos;Battle_Dungeon_Gate(Lv25General)&apos;
        ///&apos;1&apos;,&apos;ixbdp25&apos;,&apos;Battle_Dungeon_Gate(Lv25Party)&apos;
        ///&apos;2&apos;,&apos;ixbdn20&apos;,&apos;Battle_Dungeon_Gate(Lv20General)&apos;
        ///&apos;3&apos;,&apos;ixbdp20&apos;,&apos;Battle_Dungeon_Gate(Lv20Party)&apos;
        ///&apos;4&apos;,&apos;ixkey01&apos;,&apos;Gateway_Generating_Key(Wing_Battle_Dungeon15_20)&apos;
        ///&apos;5&apos;,&apos;ixkey02&apos;,&apos;Gateway_Generating_Key(Flem_Battle_Dungeon21_25)&apos;
        ///&apos;6&apos;,&apos;ixkey03&apos;,&apos;Gateway_Generating_Key(SnatcherHill_Battle_Dungeon21_25)&apos;
        ///&apos;7&apos;,&apos;ixkey04&apos;,&apos;Gateway_Generating_Key(Grumble_Battle_Dungeon26_30)&apos;
        ///&apos;8&apos;,&apos;ixkey05&apos;,&apos;Gateway_Generating_Key(Gaf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BattleDungeonItem {
            get {
                return ResourceManager.GetString("BattleDungeonItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;iyyyy01&apos;,&apos;Cling&apos;
        ///&apos;1&apos;,&apos;iyyyy02&apos;,&apos;Haren&apos;
        ///&apos;2&apos;,&apos;iyyyy03&apos;,&apos;Greaf&apos;
        ///&apos;3&apos;,&apos;iyyyy04&apos;,&apos;Rian&apos;
        ///&apos;4&apos;,&apos;iyyyy05&apos;,&apos;Mika&apos;
        ///&apos;5&apos;,&apos;iyyyy06&apos;,&apos;Louis_Mika&apos;
        ///&apos;6&apos;,&apos;iyyyy07&apos;,&apos;Mid_Mika&apos;
        ///&apos;7&apos;,&apos;iyyyy08&apos;,&apos;Weef&apos;
        ///&apos;8&apos;,&apos;iyyyy09&apos;,&apos;Cell_Weef&apos;
        ///&apos;9&apos;,&apos;iyyyy10&apos;,&apos;Ward_Weef&apos;
        ///&apos;10&apos;,&apos;iyyyy11&apos;,&apos;Lake&apos;
        ///&apos;11&apos;,&apos;iyyyy12&apos;,&apos;Riar&apos;
        ///&apos;12&apos;,&apos;iyyyy13&apos;,&apos;Jem_Riar&apos;
        ///&apos;13&apos;,&apos;iyyyy14&apos;,&apos;Jemz_Riar&apos;
        ///&apos;14&apos;,&apos;iyyyy15&apos;,&apos;Jim&apos;
        ///&apos;15&apos;,&apos;iyyyy16&apos;,&apos;Zid&apos;
        ///&apos;16&apos;,&apos;iyyyy17&apos;,&apos;Sol_Zid&apos;
        ///&apos;17&apos;,&apos;iyyyy18&apos;,&apos;High_Zid&apos;
        ///&apos;18&apos;,&apos;iyyyy19&apos;,&apos....
        /// </summary>
        internal static string BootyItem {
            get {
                return ResourceManager.GetString("BootyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;bxlow01&apos;,&apos;Bamboo_in_a_Lover&apos;
        ///&apos;1&apos;,&apos;bxchr01&apos;,&apos;Small_GiftBox&apos;
        ///&apos;2&apos;,&apos;bxchr02&apos;,&apos;GiftBox&apos;
        ///&apos;3&apos;,&apos;bxchr03&apos;,&apos;Big_GiftBox&apos;
        ///&apos;4&apos;,&apos;bxdbr01&apos;,&apos;Walnut&apos;
        ///&apos;5&apos;,&apos;bxwhi01&apos;,&apos;GiftBox&apos;
        ///&apos;6&apos;,&apos;bxbch01&apos;,&apos;Box_of_Triumph(Bellato)&apos;
        ///&apos;7&apos;,&apos;bxcch01&apos;,&apos;Box_of_Dicem(Cora)&apos;
        ///&apos;8&apos;,&apos;bxach01&apos;,&apos;Box_of_Kesar(Accretia)&apos;
        ///&apos;9&apos;,&apos;bxscr01&apos;,&apos;Symbol_of_Warrior&apos;
        ///&apos;10&apos;,&apos;bxgem01&apos;,&apos;Master`s_Small_Gift&apos;
        ///&apos;11&apos;,&apos;bxgem02&apos;,&apos;Master`s_Gift&apos;
        ///&apos;12&apos;,&apos;bxgem03&apos;,&apos;Master`s_Large_Gift&apos;
        ///&apos;13&apos;,&apos;bxxts01&apos;,&apos;Test_Server_Only_WarriorWeaponPiece&apos;
        ///&apos;14&apos;,&apos;bxxts02&apos;,&apos;Test_Server_O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BoxItem {
            get {
                return ResourceManager.GetString("BoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;ibbow01&apos;,&apos;Arrow&apos;
        ///&apos;1&apos;,&apos;ibbow02&apos;,&apos;Fire_Arrow&apos;
        ///&apos;2&apos;,&apos;ibbow03&apos;,&apos;Ice_Arrow&apos;
        ///&apos;3&apos;,&apos;ibbow04&apos;,&apos;Poison_Arrow&apos;
        ///&apos;4&apos;,&apos;ibbow05&apos;,&apos;Multi_Arrow&apos;
        ///&apos;5&apos;,&apos;ibbow06&apos;,&apos;Mineral_Arrow&apos;
        ///&apos;6&apos;,&apos;ibbow07&apos;,&apos;Exploding_Arrow&apos;
        ///&apos;7&apos;,&apos;ibbow08&apos;,&apos;Bolt&apos;
        ///&apos;8&apos;,&apos;ibbow09&apos;,&apos;Fire_Bolt&apos;
        ///&apos;9&apos;,&apos;ibbow10&apos;,&apos;Ice_Bolt&apos;
        ///&apos;10&apos;,&apos;ibbow11&apos;,&apos;Poison_Bolt&apos;
        ///&apos;11&apos;,&apos;ibbow12&apos;,&apos;Multi_Bolt&apos;
        ///&apos;12&apos;,&apos;ibbow13&apos;,&apos;Mineral_Bolt&apos;
        ///&apos;13&apos;,&apos;ibbow14&apos;,&apos;Exploding_Bolt&apos;
        ///&apos;14&apos;,&apos;ibbow15&apos;,&apos;Beam_Cell&apos;
        ///&apos;15&apos;,&apos;ibbow16&apos;,&apos;Advanced_Beam_Cell&apos;
        ///&apos;16&apos;,&apos;ibbow17&apos;,&apos;Giga_Arrow&apos;
        ///&apos;17&apos;,&ap....
        /// </summary>
        internal static string BulletItem {
            get {
                return ResourceManager.GetString("BulletItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;ikbb001&apos;,&apos;Force_Booster(BellatoCape1)&apos;
        ///&apos;1&apos;,&apos;ikbb002&apos;,&apos;Fire_Force_Booster(BellatoCape2)&apos;
        ///&apos;2&apos;,&apos;ikbb003&apos;,&apos;Aqua_Force_Booster(BellatoCape3)&apos;
        ///&apos;3&apos;,&apos;ikbb004&apos;,&apos;Terra_Force_Booster(BellatoCape4)&apos;
        ///&apos;4&apos;,&apos;ikbb005&apos;,&apos;Wind_Force_Booster(BellatoCape5)&apos;
        ///&apos;5&apos;,&apos;ikbb006&apos;,&apos;Advanced_Force_Booster(BellatoCape6)&apos;
        ///&apos;6&apos;,&apos;ikbb007&apos;,&apos;Advanced_Fire_Force_Booster(BellatoCape7)&apos;
        ///&apos;7&apos;,&apos;ikbb008&apos;,&apos;Advanced_Aqua_Force_Booster(BellatoCape8)&apos;
        ///&apos;8&apos;,&apos;ikbb009&apos;,&apos;Advanced_Terra_Booster(BellatoCape9)&apos;
        ///&apos;9&apos;,&apos;ikbb010&apos;,&apos;Advanced_Wind_Booster(Bel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CloakItem {
            get {
                return ResourceManager.GetString("CloakItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;!chathere&apos;,&apos;Notice Chat(GM Character Only)&apos;
        ///&apos;1&apos;,&apos;#chathere&apos;,&apos;GM Only Chat&apos;
        ///&apos;2&apos;,&apos;%move XXXX&apos;,&apos;Teleport to XXXX Character&apos;
        ///&apos;3&apos;,&apos;%moncall 00000 XX&apos;,&apos;Spawns a certain monster XX = Amount&apos;
        ///&apos;4&apos;,&apos;%neverdie&apos;,&apos;HP Auto Regen and Fixed SP and FP&apos;
        ///&apos;5&apos;,&apos;%beggar&apos;,&apos;Monster Drops Everything from Loot Table&apos;
        ///&apos;6&apos;,&apos;%no beggar&apos;,&apos;Turns off Beggar&apos;
        ///&apos;7&apos;,&apos;%matchless&apos;,&apos;Hit target for amount of HP they have&apos;
        ///&apos;8&apos;,&apos;%no matchless&apos;,&apos;Turns off Matchless&apos;
        ///&apos;9&apos;,&apos;%transparent&apos;,&apos;Invisible to Normal Players&apos;
        ///&apos;10&apos;,&apos;%no transparen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;cucou00&apos;,&apos;PCcafe_PremiumDiscount_Coupon[1Hr]&apos;
        ///&apos;1&apos;,&apos;cucou01&apos;,&apos;PCcafe_PremiumDiscount_Coupon[2Hr]&apos;
        ///&apos;2&apos;,&apos;cucou02&apos;,&apos;PCcafe_PremiumDiscount_Coupon[3Hr]&apos;
        ///&apos;3&apos;,&apos;cucou03&apos;,&apos;PCcafe_PremiumDiscount_Coupon[4Hr]&apos;
        ///&apos;4&apos;,&apos;cucou04&apos;,&apos;PCcafe_PremiumDiscount_Coupon[5Hr]&apos;
        ///&apos;5&apos;,&apos;cucou05&apos;,&apos;Membership_Coupon[Silver]&apos;
        ///&apos;6&apos;,&apos;cucou06&apos;,&apos;Membership_Coupon[Gold]&apos;
        ///&apos;7&apos;,&apos;cucou07&apos;,&apos;Membership_Coupon[Platinum]&apos;
        ///&apos;8&apos;,&apos;cucou08&apos;,&apos;Membership_Coupon[Emerald]&apos;
        ///&apos;9&apos;,&apos;cucou09&apos;,&apos;Membership_Coupon[Sapphire]&apos;
        ///&apos;10&apos;,&apos;cucou10&apos;,&apos;Membership_Coupon[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CouponItem {
            get {
                return ResourceManager.GetString("CouponItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;evddd01&apos;,&apos;Broken_Tombstone&apos;
        ///&apos;1&apos;,&apos;evddd02&apos;,&apos;Key_of_Darkness&apos;
        ///&apos;2&apos;,&apos;evddd03&apos;,&apos;Crystal_of_fire&apos;
        ///&apos;3&apos;,&apos;evddd04&apos;,&apos;Broken_Crystal&apos;.
        /// </summary>
        internal static string EventItem {
            get {
                return ResourceManager.GetString("EventItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;fiaaa01&apos;,&apos;FireWorkA&apos;
        ///&apos;1&apos;,&apos;fiaaa02&apos;,&apos;FireWorkB&apos;
        ///&apos;2&apos;,&apos;fiaaa03&apos;,&apos;FireWorkC&apos;
        ///&apos;3&apos;,&apos;fiaaa04&apos;,&apos;Heart&apos;
        ///&apos;4&apos;,&apos;fibbb01&apos;,&apos;Firecracker_A&apos;
        ///&apos;5&apos;,&apos;fibbb02&apos;,&apos;Firecracker_B&apos;
        ///&apos;6&apos;,&apos;fibbb03&apos;,&apos;Firecracker_C&apos;
        ///&apos;7&apos;,&apos;fibbb04&apos;,&apos;Heart_A&apos;.
        /// </summary>
        internal static string FireCracker {
            get {
                return ResourceManager.GetString("FireCracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;icfla00&apos;,&apos;Training_Prism_Shard&apos;
        ///&apos;1&apos;,&apos;icala00&apos;,&apos;Training_Ice_Shard&apos;
        ///&apos;2&apos;,&apos;ictla00&apos;,&apos;Training_Vein_Fall&apos;
        ///&apos;3&apos;,&apos;icwla00&apos;,&apos;Training_Spark&apos;
        ///&apos;4&apos;,&apos;icdls01&apos;,&apos;Celerity&apos;
        ///&apos;5&apos;,&apos;icdls02&apos;,&apos;Sacrifice&apos;
        ///&apos;6&apos;,&apos;icdls03&apos;,&apos;Tempo&apos;
        ///&apos;7&apos;,&apos;icdms01&apos;,&apos;Adept&apos;
        ///&apos;8&apos;,&apos;icdms02&apos;,&apos;Vista&apos;
        ///&apos;9&apos;,&apos;icdms03&apos;,&apos;Velocity_(Dark)&apos;
        ///&apos;10&apos;,&apos;icdhs01&apos;,&apos;Acuity&apos;
        ///&apos;11&apos;,&apos;icdhs02&apos;,&apos;Torment&apos;
        ///&apos;12&apos;,&apos;icdhs03&apos;,&apos;Conservation_(Dark)&apos;
        ///&apos;13&apos;,&apos;icdts01&apos;,&apos;Not_Available&apos;
        ///&apos;14&apos;,&apos;icdts02&apos;,&apos;Not_Available&apos;
        ///&apos;15&apos;,&apos;icdts03&apos;,&apos;Not_Available&apos;
        ///&apos;16&apos;,&apos;ichls01&apos;,&apos;Focus&apos;
        ///&apos....
        /// </summary>
        internal static string ForceItem {
            get {
                return ResourceManager.GetString("ForceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;igdbf01&apos;,&apos;Default_Bellato_Male_Gloves_1&apos;
        ///&apos;1&apos;,&apos;igdbf02&apos;,&apos;Default_Bellato_Male_Gloves_2&apos;
        ///&apos;2&apos;,&apos;igdbf03&apos;,&apos;Default_Bellato_Male_Gloves_3&apos;
        ///&apos;3&apos;,&apos;igdbf04&apos;,&apos;Default_Bellato_Male_Gloves_4&apos;
        ///&apos;4&apos;,&apos;igdbf05&apos;,&apos;Default_Bellato_Male_Gloves_5&apos;
        ///&apos;5&apos;,&apos;igdbf06&apos;,&apos;Default_Bellato_Male_Gloves_6&apos;
        ///&apos;6&apos;,&apos;igdbf07&apos;,&apos;Default_Bellato_Male_Gloves_7&apos;
        ///&apos;7&apos;,&apos;igdbf08&apos;,&apos;Default_Bellato_Male_Gloves_8&apos;
        ///&apos;8&apos;,&apos;igdbf09&apos;,&apos;Default_Bellato_Male_Gloves_9&apos;
        ///&apos;9&apos;,&apos;igdbf10&apos;,&apos;Default_Bellato_Male_Gloves_10&apos;
        ///&apos;10&apos;,&apos;igdbf11&apos;,&apos;Default_Bellato_Male_Glov [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GauntletItem {
            get {
                return ResourceManager.GetString("GauntletItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;gtbb000&apos;,&apos;Bellato_Guard_Tower(system)&apos;
        ///&apos;1&apos;,&apos;gtbb001&apos;,&apos;Light_Guard_Tower(Bellato1)&apos;
        ///&apos;2&apos;,&apos;gtbb002&apos;,&apos;Guard_Tower(Bellato2)&apos;
        ///&apos;3&apos;,&apos;gtbb003&apos;,&apos;Advanced_Guard_Tower(Bellato3)&apos;
        ///&apos;4&apos;,&apos;gtbb004&apos;,&apos;Epochal_Guard_Tower(Bellato4)&apos;
        ///&apos;5&apos;,&apos;gtbb005&apos;,&apos;Intense_Epochal_Guard_Tower(Bellato5)&apos;
        ///&apos;6&apos;,&apos;gtbb006&apos;,&apos;Hedge_Hawk(Bellato6)&apos;
        ///&apos;7&apos;,&apos;gtbb007&apos;,&apos;Advanced_Hedge_Hawk(Bellato7)&apos;
        ///&apos;8&apos;,&apos;gtbb008&apos;,&apos;Intense_Epochal_Guard_Tower_T1(Bellato8)&apos;
        ///&apos;9&apos;,&apos;gtbb009&apos;,&apos;Intense_Epochal_Guard_Tower_T2(Bellato9)&apos;
        ///&apos;10&apos;,&apos;gtbb010&apos;,&apos;Hedge_Hawk_T1(Be [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GuardTowerItem {
            get {
                return ResourceManager.GetString("GuardTowerItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;ihdbf01&apos;,&apos;Default_Bellato_Male_Helmet1&apos;
        ///&apos;1&apos;,&apos;ihdbf02&apos;,&apos;Default_Bellato_Male_Helmet2&apos;
        ///&apos;2&apos;,&apos;ihdbf03&apos;,&apos;Default_Bellato_Male_Helmet3&apos;
        ///&apos;3&apos;,&apos;ihdbf04&apos;,&apos;Default_Bellato_Male_Helmet4&apos;
        ///&apos;4&apos;,&apos;ihdbf05&apos;,&apos;Default_Bellato_Male_Helmet5&apos;
        ///&apos;5&apos;,&apos;ihdbf06&apos;,&apos;Default_Bellato_Male_Helmet6&apos;
        ///&apos;6&apos;,&apos;ihdbf07&apos;,&apos;Default_Bellato_Male_Helmet7&apos;
        ///&apos;7&apos;,&apos;ihdbf08&apos;,&apos;Default_Bellato_Male_Helmet8&apos;
        ///&apos;8&apos;,&apos;ihdbf09&apos;,&apos;Default_Bellato_Male_Helmet9&apos;
        ///&apos;9&apos;,&apos;ihdbf10&apos;,&apos;Default_Bellato_Male_Helmet10&apos;
        ///&apos;10&apos;,&apos;ihdbf11&apos;,&apos;Default_Bellato_Male_Helmet11&apos;
        ///&apos;11 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelmetItem {
            get {
                return ResourceManager.GetString("HelmetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;ildbf01&apos;,&apos;Default_Bellato_Male_Pants1&apos;
        ///&apos;1&apos;,&apos;ildbf02&apos;,&apos;Default_Bellato_Male_Pants2&apos;
        ///&apos;2&apos;,&apos;ildbf03&apos;,&apos;Default_Bellato_Male_Pants3&apos;
        ///&apos;3&apos;,&apos;ildbf04&apos;,&apos;Default_Bellato_Male_Pants4&apos;
        ///&apos;4&apos;,&apos;ildbf05&apos;,&apos;Default_Bellato_Male_Pants5&apos;
        ///&apos;5&apos;,&apos;ildbf06&apos;,&apos;Default_Bellato_Male_Pants6&apos;
        ///&apos;6&apos;,&apos;ildbf07&apos;,&apos;Default_Bellato_Male_Pants7&apos;
        ///&apos;7&apos;,&apos;ildbf08&apos;,&apos;Default_Bellato_Male_Pants8&apos;
        ///&apos;8&apos;,&apos;ildbf09&apos;,&apos;Default_Bellato_Male_Pants9&apos;
        ///&apos;9&apos;,&apos;ildbf10&apos;,&apos;Default_Bellato_Male_Pants10&apos;
        ///&apos;10&apos;,&apos;ildbf11&apos;,&apos;Default_Bellato_Male_Pants11&apos;
        ///&apos;11&apos;,&apos;ildbf12&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LowerItem {
            get {
                return ResourceManager.GetString("LowerItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;immmm01&apos;,&apos;Weapon/Shield_Tool_Kit&apos;
        ///&apos;1&apos;,&apos;immmm02&apos;,&apos;Armor_Tool_Kit&apos;
        ///&apos;2&apos;,&apos;immmm03&apos;,&apos;Bullet_Tool_Kit&apos;
        ///&apos;3&apos;,&apos;immmm04&apos;,&apos;Upgrader&apos;
        ///&apos;4&apos;,&apos;imleo01&apos;,&apos;Leon`s_Blueprint&apos;
        ///&apos;5&apos;,&apos;imbal01&apos;,&apos;World_Cup_Event_Ball(Bellato)&apos;
        ///&apos;6&apos;,&apos;imbal02&apos;,&apos;World_Cup_Event_Ball(Cora)&apos;
        ///&apos;7&apos;,&apos;imbal03&apos;,&apos;World_Cup_Event_Ball(Acc)&apos;.
        /// </summary>
        internal static string MakeToolItem {
            get {
                return ResourceManager.GetString("MakeToolItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;izbbb00&apos;,&apos;Training_Bellato_HQ(Map)&apos;
        ///&apos;1&apos;,&apos;izccc00&apos;,&apos;Training_Cora_HQ(Map)&apos;
        ///&apos;2&apos;,&apos;izaaa00&apos;,&apos;Training_Accretia_HQ(Map)&apos;
        ///&apos;3&apos;,&apos;izbbb01&apos;,&apos;Bellato_HQ(Map)&apos;
        ///&apos;4&apos;,&apos;izccc01&apos;,&apos;Cora_HQ(Map)&apos;
        ///&apos;5&apos;,&apos;izaaa01&apos;,&apos;Accretia_HQ(Map)&apos;
        ///&apos;6&apos;,&apos;izbnn01&apos;,&apos;Solus_Settlement(Map)&apos;
        ///&apos;7&apos;,&apos;izbnn02&apos;,&apos;Anacaade_Settlement(Map)&apos;
        ///&apos;8&apos;,&apos;izcnn01&apos;,&apos;Haram_Stockade(Map)&apos;
        ///&apos;9&apos;,&apos;izcnn02&apos;,&apos;Numerus_Stockade(Map)&apos;
        ///&apos;10&apos;,&apos;izann01&apos;,&apos;Armory-213(Map)&apos;
        ///&apos;11&apos;,&apos;izann02&apos;,&apos;Armory-117(Map)&apos;
        ///&apos;12&apos;,&apos;izree01&apos;,&apos;Crag_Mine_Field(Map)&apos;
        ///&apos;13&apos;,&apos;izpll01&apos;,&apos;Ether_Platf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MapItem {
            get {
                return ResourceManager.GetString("MapItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;00000&apos;,&apos;Young_Flem(A)&apos;
        ///&apos;1&apos;,&apos;00001&apos;,&apos;Young_Flem(B)&apos;
        ///&apos;2&apos;,&apos;00002&apos;,&apos;Young_Flem(C)&apos;
        ///&apos;3&apos;,&apos;00100&apos;,&apos;Wing(A)&apos;
        ///&apos;4&apos;,&apos;00101&apos;,&apos;Wing(B)&apos;
        ///&apos;5&apos;,&apos;00102&apos;,&apos;Wing(C)&apos;
        ///&apos;6&apos;,&apos;00300&apos;,&apos;Deser_Klan(A)&apos;
        ///&apos;7&apos;,&apos;00301&apos;,&apos;Deser_Klan(B)&apos;
        ///&apos;8&apos;,&apos;00201&apos;,&apos;Flem(B)&apos;
        ///&apos;9&apos;,&apos;00202&apos;,&apos;Flem(C)&apos;
        ///&apos;10&apos;,&apos;00200&apos;,&apos;Flem(A)&apos;
        ///&apos;11&apos;,&apos;00500&apos;,&apos;Stink_Bug(A)&apos;
        ///&apos;12&apos;,&apos;00501&apos;,&apos;Stink_Bug(B)&apos;
        ///&apos;13&apos;,&apos;00302&apos;,&apos;Deser_Klan(C)&apos;
        ///&apos;14&apos;,&apos;00600&apos;,&apos;Heavy_Wing(A)&apos;
        ///&apos;15&apos;,&apos;00400&apos;,&apos;Flem_Guard(A)&apos;
        ///&apos;16&apos;,&apos;00401&apos;,&apos;Flem_Guard(B)&apos;
        ///&apos;17&apos;,&apos;00402&apos;,&apos;Flem_Guard....
        /// </summary>
        internal static string MonsterCharacter {
            get {
                return ResourceManager.GetString("MonsterCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;lknpc00&apos;,&apos;UMT_Disposable_Pager(B)&apos;
        ///&apos;1&apos;,&apos;lknpc01&apos;,&apos;UMT_Pager(B)&apos;
        ///&apos;2&apos;,&apos;lknpc02&apos;,&apos;UMT_Disposable_Pager(C)&apos;
        ///&apos;3&apos;,&apos;lknpc03&apos;,&apos;UMT_Pager(C)&apos;
        ///&apos;4&apos;,&apos;lknpc04&apos;,&apos;UMT_Disposable_Pager(A)&apos;
        ///&apos;5&apos;,&apos;lknpc05&apos;,&apos;UMT_Pager(A)&apos;
        ///&apos;6&apos;,&apos;lknpc06&apos;,&apos;Storage_Disposable_Beeper(B)&apos;
        ///&apos;7&apos;,&apos;lknpc07&apos;,&apos;Storage_Beeper(B)&apos;
        ///&apos;8&apos;,&apos;lknpc08&apos;,&apos;Storage_Disposable_Beeper(C)&apos;
        ///&apos;9&apos;,&apos;lknpc09&apos;,&apos;Storage_Beeper(C)&apos;
        ///&apos;10&apos;,&apos;lknpc10&apos;,&apos;Storage_Disposable_Beeper(A)&apos;
        ///&apos;11&apos;,&apos;lknpc11&apos;,&apos;Warehouse_Beeper(A)&apos;
        ///&apos;12&apos;,&apos;lknpc12&apos;,&apos;Combination_Disposable_Beeper(B)&apos;
        ///&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NPCLinkItem {
            get {
                return ResourceManager.GetString("NPCLinkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;ioblu03&apos;,&apos;Blue_Ore+3&apos;
        ///&apos;1&apos;,&apos;ioblu02&apos;,&apos;Blue_Ore+2&apos;
        ///&apos;2&apos;,&apos;ioblu01&apos;,&apos;Blue_Ore+1&apos;
        ///&apos;3&apos;,&apos;iored03&apos;,&apos;Red_Ore+3&apos;
        ///&apos;4&apos;,&apos;iored02&apos;,&apos;Red_Ore+2&apos;
        ///&apos;5&apos;,&apos;iored01&apos;,&apos;Red_Ore+1&apos;
        ///&apos;6&apos;,&apos;ioyel03&apos;,&apos;Yellow_Ore+3&apos;
        ///&apos;7&apos;,&apos;ioyel02&apos;,&apos;Yellow_Ore+2&apos;
        ///&apos;8&apos;,&apos;ioyel01&apos;,&apos;Yellow_Ore+1&apos;
        ///&apos;9&apos;,&apos;iogre03&apos;,&apos;Green_Ore+3&apos;
        ///&apos;10&apos;,&apos;iogre02&apos;,&apos;Green_Ore+2&apos;
        ///&apos;11&apos;,&apos;iogre01&apos;,&apos;Green_Ore+1&apos;
        ///&apos;12&apos;,&apos;iobla03&apos;,&apos;Black_Ore+3&apos;
        ///&apos;13&apos;,&apos;iobla02&apos;,&apos;Black_Ore+2&apos;
        ///&apos;14&apos;,&apos;iobla01&apos;,&apos;Black_Ore+1&apos;
        ///&apos;15&apos;,&apos;ioblu04&apos;,&apos;Blue_Ore+4&apos;
        ///&apos;16&apos;,&apos;iored04&apos;,&apos;Red_Ore+4&apos;
        ///&apos;17&apos;,&apos....
        /// </summary>
        internal static string OreItem {
            get {
                return ResourceManager.GetString("OreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;ipbhp01&apos;,&apos;Bless_HP_Potion_100&apos;
        ///&apos;1&apos;,&apos;ipbhp02&apos;,&apos;Bless_HP_Potion_250&apos;
        ///&apos;2&apos;,&apos;ipbhp03&apos;,&apos;Bless_HP_Potion_500&apos;
        ///&apos;3&apos;,&apos;ipbhp04&apos;,&apos;Bless_HP_Potion_1000&apos;
        ///&apos;4&apos;,&apos;ipbhp05&apos;,&apos;Bless_HP_Potion_2000&apos;
        ///&apos;5&apos;,&apos;ipbhp06&apos;,&apos;Bless_HP_Potion_3000&apos;
        ///&apos;6&apos;,&apos;ipbhp07&apos;,&apos;Bless_HP_Potion_4000&apos;
        ///&apos;7&apos;,&apos;ipbhp08&apos;,&apos;Bless_HP_Potion_5000&apos;
        ///&apos;8&apos;,&apos;ipchp01&apos;,&apos;Pope_HP_Potion_100&apos;
        ///&apos;9&apos;,&apos;ipchp02&apos;,&apos;Pope_HP_Potion_250&apos;
        ///&apos;10&apos;,&apos;ipchp03&apos;,&apos;Pope_HP_Potion_500&apos;
        ///&apos;11&apos;,&apos;ipchp04&apos;,&apos;Pope_HP_Potion_1000&apos;
        ///&apos;12&apos;,&apos;ipchp05&apos;,&apos;Pope_HP_Potion_2000&apos;
        ///&apos;13&apos;,&apos;ipchp06&apos;,&apos;Pope_HP_Po [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PotionItem {
            get {
                return ResourceManager.GetString("PotionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;QI00000&apos;,&apos;Flym_Guard_armor&apos;
        ///&apos;1&apos;,&apos;QI00100&apos;,&apos;WarBeast_horn&apos;
        ///&apos;2&apos;,&apos;QI00200&apos;,&apos;Gaff_Tail_poisoned_needle&apos;
        ///&apos;3&apos;,&apos;QI00300&apos;,&apos;Lapise_backplate&apos;
        ///&apos;4&apos;,&apos;QI00400&apos;,&apos;Stingbug_skin&apos;
        ///&apos;5&apos;,&apos;QI00500&apos;,&apos;Lunker_leather&apos;
        ///&apos;6&apos;,&apos;QI00600&apos;,&apos;Twiser_claws&apos;
        ///&apos;7&apos;,&apos;QI00700&apos;,&apos;HeavyWing_chip&apos;
        ///&apos;8&apos;,&apos;QI00800&apos;,&apos;Lizard_backplate&apos;
        ///&apos;9&apos;,&apos;QI00900&apos;,&apos;Archer_Bow&apos;
        ///&apos;10&apos;,&apos;QI00901&apos;,&apos;Sickle_staff&apos;
        ///&apos;11&apos;,&apos;QI00902&apos;,&apos;Scout_glove&apos;
        ///&apos;12&apos;,&apos;QI00903&apos;,&apos;Queen_Crook_claws&apos;
        ///&apos;13&apos;,&apos;QI00904&apos;,&apos;Caster_head_decoration&apos;
        ///&apos;14&apos;,&apos;QI00905&apos;,&apos;Sermoner_hear_decoration&apos;
        ///&apos;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuestItem {
            get {
                return ResourceManager.GetString("QuestItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;rdaaa01&apos;,&apos;Satellite_Radar(1)&apos;
        ///&apos;1&apos;,&apos;rdaaa02&apos;,&apos;High-Speed_Satellite_Radar(2)&apos;
        ///&apos;2&apos;,&apos;rdaaa03&apos;,&apos;Ultra_Satellite_Radar(3)&apos;
        ///&apos;3&apos;,&apos;rdpvp01&apos;,&apos;Satellite_Radar(1)&apos;
        ///&apos;4&apos;,&apos;rdpvp02&apos;,&apos;High-Speed_Satellite_Radar(2)&apos;
        ///&apos;5&apos;,&apos;rdpvp03&apos;,&apos;Ultra_Satellite_Radar(3)&apos;.
        /// </summary>
        internal static string RadarItem {
            get {
                return ResourceManager.GetString("RadarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;rebbb01&apos;,&apos;Recovery_Item_A(1)&apos;
        ///&apos;1&apos;,&apos;rebbb02&apos;,&apos;Recovery_Item_B(2)&apos;
        ///&apos;2&apos;,&apos;rebbb03&apos;,&apos;Recovery_Item_C(3)&apos;
        ///&apos;3&apos;,&apos;rebbb04&apos;,&apos;Recovery_Item_D(4)&apos;
        ///&apos;4&apos;,&apos;rebbb05&apos;,&apos;Recovery_Item_E(5)&apos;
        ///&apos;5&apos;,&apos;rebbb06&apos;,&apos;Recovery_Item_F(6)&apos;
        ///&apos;6&apos;,&apos;rebbb07&apos;,&apos;Recovery_Item_G(7)&apos;
        ///&apos;7&apos;,&apos;rebbb08&apos;,&apos;Recovery_Item_H(8)&apos;
        ///&apos;8&apos;,&apos;rebbb09&apos;,&apos;Recovery_Item_I(9)&apos;
        ///&apos;9&apos;,&apos;rebbb10&apos;,&apos;Recovery_Item_J(10)&apos;
        ///&apos;10&apos;,&apos;rebbb11&apos;,&apos;Lucky_accessory&apos;
        ///&apos;11&apos;,&apos;recsa01&apos;,&apos;Experience_Point100%_RecoverCapsule[Premium](Cash)&apos;.
        /// </summary>
        internal static string RecoveryItem {
            get {
                return ResourceManager.GetString("RecoveryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;irriu01&apos;,&apos;Fetalium&apos;
        ///&apos;1&apos;,&apos;irriu02&apos;,&apos;Lutalium&apos;
        ///&apos;2&apos;,&apos;irriu03&apos;,&apos;Ostalium&apos;
        ///&apos;3&apos;,&apos;irriu04&apos;,&apos;Haitalium&apos;
        ///&apos;4&apos;,&apos;irriu05&apos;,&apos;Firstalium&apos;
        ///&apos;5&apos;,&apos;irrio01&apos;,&apos;Cotalrio&apos;
        ///&apos;6&apos;,&apos;irrio02&apos;,&apos;Lotalrio&apos;
        ///&apos;7&apos;,&apos;irrio03&apos;,&apos;Iritalrio&apos;
        ///&apos;8&apos;,&apos;irrio04&apos;,&apos;Metalrio&apos;
        ///&apos;9&apos;,&apos;irrio05&apos;,&apos;Utalrio&apos;
        ///&apos;10&apos;,&apos;irrus01&apos;,&apos;Baytalrous&apos;
        ///&apos;11&apos;,&apos;irrus02&apos;,&apos;Niotalrous&apos;
        ///&apos;12&apos;,&apos;irrus03&apos;,&apos;Teitalrous&apos;
        ///&apos;13&apos;,&apos;irrus04&apos;,&apos;Dutalrous&apos;
        ///&apos;14&apos;,&apos;irrus05&apos;,&apos;Protalrous&apos;
        ///&apos;15&apos;,&apos;irria01&apos;,&apos;Crotalian&apos;
        ///&apos;16&apos;,&apos;irria02&apos;,&apos;Motalian&apos;
        ///&apos;17&apos;,&apos;irria03&apos;,&apos;Tutalian....
        /// </summary>
        internal static string ResourceItem {
            get {
                return ResourceManager.GetString("ResourceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;iibba01&apos;,&apos;Fire_Parsal_WristletA(1)&apos;
        ///&apos;1&apos;,&apos;iibba02&apos;,&apos;Fire_Parsal_WristletB(2)&apos;
        ///&apos;2&apos;,&apos;iibba03&apos;,&apos;Fire_Parsal_WristletC(3)&apos;
        ///&apos;3&apos;,&apos;iibba04&apos;,&apos;Fire_Parsal_WristletD(4)&apos;
        ///&apos;4&apos;,&apos;iibba05&apos;,&apos;Fire_Parsal_WristletE(5)&apos;
        ///&apos;5&apos;,&apos;iibba06&apos;,&apos;Fire_Parsal_WristletF(6)&apos;
        ///&apos;6&apos;,&apos;iibba07&apos;,&apos;Fire_Parsal_WristletG(7)&apos;
        ///&apos;7&apos;,&apos;iibba08&apos;,&apos;Aqua_Parsal_WristletA(1)&apos;
        ///&apos;8&apos;,&apos;iibba09&apos;,&apos;Aqua_Parsal_WristletA(1)&apos;
        ///&apos;9&apos;,&apos;iibba10&apos;,&apos;Aqua_Parsal_WristletB(2)&apos;
        ///&apos;10&apos;,&apos;iibba11&apos;,&apos;Aqua_Parsal_WristletC(3)&apos;
        ///&apos;11&apos;,&apos;iibba12&apos;,&apos;Aqua_Parsal_WristletD(4)&apos;
        ///&apos;12&apos;,&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RingItem {
            get {
                return ResourceManager.GetString("RingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;idbca04&apos;,&apos;Round_Shield&apos;
        ///&apos;1&apos;,&apos;idbcb04&apos;,&apos;Intense_Round_Shield&apos;
        ///&apos;2&apos;,&apos;idbcc04&apos;,&apos;Shield1C&apos;
        ///&apos;3&apos;,&apos;idbcd04&apos;,&apos;Shield1D&apos;
        ///&apos;4&apos;,&apos;idbca07&apos;,&apos;Buckler&apos;
        ///&apos;5&apos;,&apos;idbcb07&apos;,&apos;Intense_Buckler&apos;
        ///&apos;6&apos;,&apos;idbcc07&apos;,&apos;Shield2C&apos;
        ///&apos;7&apos;,&apos;idbcd07&apos;,&apos;Shield2D&apos;
        ///&apos;8&apos;,&apos;idbca10&apos;,&apos;Targe&apos;
        ///&apos;9&apos;,&apos;idbcb10&apos;,&apos;Intense_Targe&apos;
        ///&apos;10&apos;,&apos;idbcc10&apos;,&apos;Shield3C&apos;
        ///&apos;11&apos;,&apos;idbcd10&apos;,&apos;Shield3D&apos;
        ///&apos;12&apos;,&apos;idbca13&apos;,&apos;Large_Shield&apos;
        ///&apos;13&apos;,&apos;idbcb13&apos;,&apos;Intense_Large_Shield&apos;
        ///&apos;14&apos;,&apos;idbcc13&apos;,&apos;Shield4C&apos;
        ///&apos;15&apos;,&apos;idbcd13&apos;,&apos;Shield4D&apos;
        ///&apos;16&apos;,&apos;idbca16&apos;,&apos;Kite_Shield&apos;
        ///&apos;17&apos;,&apo....
        /// </summary>
        internal static string ShieldItem {
            get {
                return ResourceManager.GetString("ShieldItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;isdbf01&apos;,&apos;Default_Bellato_Male_Shoes1&apos;
        ///&apos;1&apos;,&apos;isdbf02&apos;,&apos;Default_Bellato_Male_Shoes2&apos;
        ///&apos;2&apos;,&apos;isdbf03&apos;,&apos;Default_Bellato_Male_Shoes3&apos;
        ///&apos;3&apos;,&apos;isdbf04&apos;,&apos;Default_Bellato_Male_Shoes4&apos;
        ///&apos;4&apos;,&apos;isdbf05&apos;,&apos;Default_Bellato_Male_Shoes5&apos;
        ///&apos;5&apos;,&apos;isdbf06&apos;,&apos;Default_Bellato_Male_Shoes6&apos;
        ///&apos;6&apos;,&apos;isdbf07&apos;,&apos;Default_Bellato_Male_Shoes7&apos;
        ///&apos;7&apos;,&apos;isdbf08&apos;,&apos;Default_Bellato_Male_Shoes8&apos;
        ///&apos;8&apos;,&apos;isdbf09&apos;,&apos;Default_Bellato_Male_Shoes9&apos;
        ///&apos;9&apos;,&apos;isdbf10&apos;,&apos;Default_Bellato_Male_Shoes10&apos;
        ///&apos;10&apos;,&apos;isdbf11&apos;,&apos;Default_Bellato_Male_Shoes11&apos;
        ///&apos;11&apos;,&apos;isdbf12&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShoeItem {
            get {
                return ResourceManager.GetString("ShoeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;sklu001&apos;,&apos;Siege_Kit(Launcher)&apos;
        ///&apos;1&apos;,&apos;sklu002&apos;,&apos;Advanced_Siege_Kit(Launcher)&apos;
        ///&apos;2&apos;,&apos;sklu003&apos;,&apos;Attack_Epochal_Siege_Kit(Launcher)&apos;
        ///&apos;3&apos;,&apos;sklu004&apos;,&apos;Defence_Epochal_Siege_Kit(Launcher)&apos;
        ///&apos;4&apos;,&apos;sklu005&apos;,&apos;Sniper_Lecas_Siege_Kit(LauncherUse)&apos;
        ///&apos;5&apos;,&apos;sklu006&apos;,&apos;Siege_Kit(Extra)&apos;
        ///&apos;6&apos;,&apos;sklu007&apos;,&apos;Shining_Siege_Kit&apos;
        ///&apos;7&apos;,&apos;sklu008&apos;,&apos;Advanced_Shining_Siege_Kit&apos;
        ///&apos;8&apos;,&apos;sklu009&apos;,&apos;Siege_Kit(Extra)&apos;
        ///&apos;9&apos;,&apos;sklu010&apos;,&apos;Siege_Kit(Extra)&apos;
        ///&apos;10&apos;,&apos;sklu011&apos;,&apos;Siege_Kit(Ejector)&apos;
        ///&apos;11&apos;,&apos;sklu012&apos;,&apos;Advanced_Siege_Kit(Ejector)&apos;
        ///&apos;12&apos;,&apos;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SiegeKitItem {
            get {
                return ResourceManager.GetString("SiegeKitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;tibp000&apos;,&apos;Cartella_Air_Transpo_Ticket:_Bellato_HQ_to_Ether_Platfrom&apos;
        ///&apos;1&apos;,&apos;ticp000&apos;,&apos;Cartella_Air_Transpo_Ticket:_Cora_HQ_to_Ether_Platfrom&apos;
        ///&apos;2&apos;,&apos;tiap000&apos;,&apos;Cartella_Air_Transpo_Ticket:_Accretia_HQ_to_Ether_Platform&apos;
        ///&apos;3&apos;,&apos;tipb000&apos;,&apos;Cartella_Air_Transpo_Ticket:_Ether_Platform_to_Bellato_HQ&apos;
        ///&apos;4&apos;,&apos;tipc000&apos;,&apos;Cartella_Air_Transpo_Ticket:_Ether_Platform_to_Cora_HQ&apos;
        ///&apos;5&apos;,&apos;tipa000&apos;,&apos;Cartella_Air_Transpo_Ticket:_Ether_Platform_to_Accretia_HQ&apos;
        ///&apos;6&apos;,&apos;tibp001&apos;,&apos;Cartella_Air_Transpo_Ticket:_Bellato_HQ_to_Ether_Pl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TicketItem {
            get {
                return ResourceManager.GetString("TicketItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;iqbbb00&apos;,&apos;Training_Bellato_HQ&apos;
        ///&apos;1&apos;,&apos;iqccc00&apos;,&apos;Training_Cora_HQ&apos;
        ///&apos;2&apos;,&apos;iqaaa00&apos;,&apos;Training_Accretia_HQ&apos;
        ///&apos;3&apos;,&apos;iqbbb01&apos;,&apos;Bellato_HQ&apos;
        ///&apos;4&apos;,&apos;iqccc01&apos;,&apos;Cora_HQ&apos;
        ///&apos;5&apos;,&apos;iqaaa01&apos;,&apos;Accretia_HQ&apos;
        ///&apos;6&apos;,&apos;iqbbb02&apos;,&apos;Bellato_Outpost&apos;
        ///&apos;7&apos;,&apos;iqccc02&apos;,&apos;Cora_Outpost&apos;
        ///&apos;8&apos;,&apos;iqaaa02&apos;,&apos;Accretia_Outpost&apos;
        ///&apos;9&apos;,&apos;iqbnn01&apos;,&apos;Solus_Settlement&apos;
        ///&apos;10&apos;,&apos;iqbnn02&apos;,&apos;Anacaade_Settlement&apos;
        ///&apos;11&apos;,&apos;iqcnn01&apos;,&apos;Haram_Stockade&apos;
        ///&apos;12&apos;,&apos;iqcnn02&apos;,&apos;Numerus_Stockade&apos;
        ///&apos;13&apos;,&apos;iqann01&apos;,&apos;Armory-213&apos;
        ///&apos;14&apos;,&apos;iqann02&apos;,&apos;Armory-117&apos;
        ///&apos;15&apos;,&apos;iqres01&apos;,&apos;Crag_Mine_ [rest of string was truncated]&qu....
        /// </summary>
        internal static string TOWNItem {
            get {
                return ResourceManager.GetString("TOWNItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;tr00001&apos;,&apos;Blasting_Powder&apos;
        ///&apos;1&apos;,&apos;tr00002&apos;,&apos;Advanced_Blasting_Powder&apos;
        ///&apos;2&apos;,&apos;tr00003&apos;,&apos;Epochal_Blasting_Powder&apos;
        ///&apos;3&apos;,&apos;tr00004&apos;,&apos;Ankle_Mine_Against_Humans&apos;
        ///&apos;4&apos;,&apos;tr00005&apos;,&apos;Booby_Trap&apos;
        ///&apos;5&apos;,&apos;tr00006&apos;,&apos;Plasma_Mine&apos;
        ///&apos;6&apos;,&apos;tr00007&apos;,&apos;Advanced_Plasma_Mine&apos;
        ///&apos;7&apos;,&apos;tr00008&apos;,&apos;Flare_Trap&apos;
        ///&apos;8&apos;,&apos;tr00009&apos;,&apos;Advanced_Flare_Trap&apos;
        ///&apos;9&apos;,&apos;tr00010&apos;,&apos;Nuclear_Mine&apos;
        ///&apos;10&apos;,&apos;tr00011&apos;,&apos;Fire_Mine&apos;
        ///&apos;11&apos;,&apos;tr00012&apos;,&apos;BoobyTrap_T1&apos;
        ///&apos;12&apos;,&apos;tr00013&apos;,&apos;BoobyTrap_T2&apos;
        ///&apos;13&apos;,&apos;tr00014&apos;,&apos;Plasma_Mine_T1&apos;
        ///&apos;14&apos;,&apos;tr00015&apos;,&apos;Plasma_Mine_T2&apos;
        ///&apos;15&apos;,&apos;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrapItem {
            get {
                return ResourceManager.GetString("TrapItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;inbbb01&apos;,&apos;Goliath&apos;
        ///&apos;1&apos;,&apos;inbbb02&apos;,&apos;Catapult&apos;
        ///&apos;2&apos;,&apos;inbbb03&apos;,&apos;Engineer&apos;
        ///&apos;3&apos;,&apos;inbbb04&apos;,&apos;Nomad&apos;.
        /// </summary>
        internal static string UnitKeyItem {
            get {
                return ResourceManager.GetString("UnitKeyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;unbb000&apos;,&apos;Advanced_UnmannedMiningTool(Bellato)&apos;
        ///&apos;1&apos;,&apos;unbb001&apos;,&apos;Advanced_UnmannedMiningTool(BellatoPC)&apos;
        ///&apos;2&apos;,&apos;uncc000&apos;,&apos;Advanced_UnmannedMiningTool(Cora)&apos;
        ///&apos;3&apos;,&apos;uncc001&apos;,&apos;Advanced_UnmannedMiningTool(CoraPC)&apos;
        ///&apos;4&apos;,&apos;unaa000&apos;,&apos;Advanced_UnmannedMiningTool(Accretia)&apos;
        ///&apos;5&apos;,&apos;unaa001&apos;,&apos;Advanced_UnmannedMiningTool(AccretiaPC)&apos;
        ///&apos;6&apos;,&apos;unbb002&apos;,&apos;Normal_UnmannedMiningTool(Bellato)&apos;
        ///&apos;7&apos;,&apos;uncc002&apos;,&apos;Normal_UnmannedMiningTool(Cora)&apos;
        ///&apos;8&apos;,&apos;unaa002&apos;,&apos;Normal_UnmannedMiningTool(Accretia)&apos;
        ///&apos;9&apos;,&apos;unbb003&apos;,&apos;Light_UnmannedMin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UNmannedminer {
            get {
                return ResourceManager.GetString("UNmannedminer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;iudbf01&apos;,&apos;Default_Bellato_Male_Shirt1&apos;
        ///&apos;1&apos;,&apos;iudbf02&apos;,&apos;Default_Bellato_Male_Shirt1&apos;
        ///&apos;2&apos;,&apos;iudbf03&apos;,&apos;Default_Bellato_Male_Shirt3&apos;
        ///&apos;3&apos;,&apos;iudbf04&apos;,&apos;Default_Bellato_Male_Shirt4&apos;
        ///&apos;4&apos;,&apos;iudbf05&apos;,&apos;Default_Bellato_Male_Shirt5&apos;
        ///&apos;5&apos;,&apos;iudbf06&apos;,&apos;Default_Bellato_Male_Shirt6&apos;
        ///&apos;6&apos;,&apos;iudbf07&apos;,&apos;Default_Bellato_Male_Shirt7&apos;
        ///&apos;7&apos;,&apos;iudbf08&apos;,&apos;Default_Bellato_Male_Shirt8&apos;
        ///&apos;8&apos;,&apos;iudbf09&apos;,&apos;Default_Bellato_Male_Shirt9&apos;
        ///&apos;9&apos;,&apos;iudbf10&apos;,&apos;Default_Bellato_Male_Shirt10&apos;
        ///&apos;10&apos;,&apos;iudbf11&apos;,&apos;Default_Bellato_Male_Shirt11&apos;
        ///&apos;11&apos;,&apos;iudbf12&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpperItem {
            get {
                return ResourceManager.GetString("UpperItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;0&apos;,&apos;iwkna01&apos;,&apos;Dagger(A)&apos;
        ///&apos;1&apos;,&apos;iwknb01&apos;,&apos;Intense_Dagger(B)&apos;
        ///&apos;2&apos;,&apos;iwknc01&apos;,&apos;Dagger(C)&apos;
        ///&apos;3&apos;,&apos;iwknd01&apos;,&apos;Kamasoon_Sword(D)&apos;
        ///&apos;4&apos;,&apos;iwkna02&apos;,&apos;Dirk(A)&apos;
        ///&apos;5&apos;,&apos;iwknb02&apos;,&apos;Intense_Dirk(B)&apos;
        ///&apos;6&apos;,&apos;iwknc02&apos;,&apos;Dirk(C)&apos;
        ///&apos;7&apos;,&apos;iwknz02&apos;,&apos;Izen_Ritter`s_Back_Blade(High11)&apos;
        ///&apos;8&apos;,&apos;iwkna03&apos;,&apos;Kukri(A)&apos;
        ///&apos;9&apos;,&apos;iwknb03&apos;,&apos;Intense_Kukri(B)&apos;
        ///&apos;10&apos;,&apos;iwknc03&apos;,&apos;Kukri(C)&apos;
        ///&apos;11&apos;,&apos;iwknz03&apos;,&apos;Izen_Ritter`s_sealed_Back_Blade(Low11)&apos;
        ///&apos;12&apos;,&apos;iwkna04&apos;,&apos;Knife4(A)&apos;
        ///&apos;13&apos;,&apos;iwknb04&apos;,&apos;Intense_Knife4(B)&apos;
        ///&apos;14&apos;,&apos;iwknc04&apos;,&apos;Knife4(C)&apos;
        ///&apos;15&apos;,&apos;iwknd04&apos;,&apos;Kni [rest of string was truncated]&qu....
        /// </summary>
        internal static string WeaponItem {
            get {
                return ResourceManager.GetString("WeaponItem", resourceCulture);
            }
        }
    }
}
